import type { Command, ModuleId } from "./types";

export const MODULE_LABELS: Record<ModuleId, string> = {
  general: "General",
  economy: "Economy",
  casino: "Casino",
  life: "Life",
};

export const COMMANDS: Command[] = [
  // ── general ────────────────────────────────────────────────
  {
    id: "help",
    name: "!help",
    aliases: [],
    module: "general",
    short:
      "The full command catalog, paginated and searchable — every module, one menu, zero guesswork.",
    usage: "!help",
    examples: ["!help"],
    interactive: true,
  },
  {
    id: "casino",
    name: "!casino",
    aliases: ["games", "casinoguide", "casino-guide"],
    module: "general",
    short:
      "The casino floor map — guides for every table before you sit down and lose your shirt.",
    usage: "!casino",
    examples: ["!casino"],
    interactive: true,
  },
  {
    id: "tutorial",
    name: "!tutorial",
    aliases: ["guide"],
    module: "general",
    short:
      "New Player Path plus sixteen lessons on how the whole economy fits together.",
    usage: "!tutorial",
    examples: ["!tutorial"],
    interactive: true,
  },
  {
    id: "start",
    name: "!start",
    aliases: [],
    module: "general",
    short:
      "Opens your account and hands you a starting stake. Everyone begins here.",
    usage: "!start",
    examples: ["!start"],
    keyNumbers: [{ label: "Starting balance", value: "1,000" }],
  },
  {
    id: "ping",
    name: "!ping",
    aliases: ["latency"],
    module: "general",
    short:
      "A gut-check on Fortuna's vitals — API, database, and Redis latency, at a glance.",
    usage: "!ping",
    examples: ["!ping"],
  },

  // ── economy ────────────────────────────────────────────────
  {
    id: "balance",
    name: "!balance",
    aliases: ["bal", "b"],
    module: "economy",
    short: "Wallet, bank, and net worth — the only number that actually matters.",
    usage: "!balance [@user]",
    args: [
      { name: "@user", desc: "Check someone else's balance instead of your own." },
    ],
    examples: ["!balance", "!bal @Someone"],
  },
  {
    id: "deposit",
    name: "!deposit",
    aliases: ["dep", "depo"],
    module: "economy",
    short:
      "Moves wallet cash into the bank, where robbers and the tax man can't touch it.",
    usage: "!deposit <amount|all>",
    args: [
      { name: "amount|all", desc: 'Amount to deposit, or "all" to sweep your wallet.' },
    ],
    examples: ["!deposit 50000", "!deposit all"],
    jailBlocked: true,
  },
  {
    id: "withdraw",
    name: "!withdraw",
    aliases: ["with", "wd"],
    module: "economy",
    short:
      "Pulls cash back out of the bank and into your wallet, where it's spendable again.",
    usage: "!withdraw <amount|all>",
    args: [
      { name: "amount|all", desc: 'Amount to withdraw, or "all" to empty the account.' },
    ],
    examples: ["!withdraw 50000", "!withdraw all"],
    jailBlocked: true,
  },
  {
    id: "transfer",
    name: "!transfer",
    aliases: ["give"],
    module: "economy",
    short: "Sends Fortunes to another player. The taxman takes a cut on the way out.",
    usage: "!transfer <@user> <amount>",
    args: [
      { name: "@user", desc: "Who receives the money." },
      { name: "amount", desc: "How much to send from your wallet." },
    ],
    examples: ["!transfer @Someone 25000"],
    keyNumbers: [{ label: "Transfer tax", value: "5%" }],
    jailBlocked: true,
  },
  {
    id: "ask",
    name: "!ask",
    aliases: ["ask-money", "askmoney"],
    module: "economy",
    short:
      "Sends a money-request card with Accept, Decline, and Block buttons. Politeness optional.",
    usage: "!ask <@user> <amount> [reason]",
    args: [
      { name: "@user", desc: "Who you're asking." },
      { name: "amount", desc: "How much you want." },
      { name: "reason", desc: "Optional excuse." },
      { name: "unblock <@user>", desc: "Lift a block you placed earlier." },
    ],
    examples: ["!ask @Someone 10000 rent money", "!ask unblock @Someone"],
    interactive: true,
  },
  {
    id: "crime",
    name: "!crime",
    aliases: [],
    module: "economy",
    short: "High-risk button board — decent odds, real prison time if you flub it.",
    usage: "!crime",
    examples: ["!crime"],
    cooldown: "1 hour",
    keyNumbers: [
      { label: "Win rate", value: "35%" },
      { label: "Payout", value: "100,000 – 220,000" },
      { label: "Fine on fail", value: "60,000 – 140,000" },
      { label: "Heat gained", value: "+20" },
    ],
    interactive: true,
    jailBlocked: true,
  },
  {
    id: "beg",
    name: "!beg",
    aliases: [],
    module: "economy",
    short: "Low-risk, low-reward. Dignity not included, but the odds are kind.",
    usage: "!beg",
    examples: ["!beg"],
    cooldown: "45 sec",
    keyNumbers: [
      { label: "Win rate", value: "70%" },
      { label: "Payout", value: "8,000 – 15,000" },
    ],
    jailBlocked: true,
  },
  {
    id: "slut",
    name: "!slut",
    aliases: [],
    module: "economy",
    short: "Slightly riskier than begging, slightly better paid. No further questions.",
    usage: "!slut",
    examples: ["!slut"],
    cooldown: "2 min",
    keyNumbers: [
      { label: "Win rate", value: "55%" },
      { label: "Payout", value: "12,000 – 22,000" },
    ],
    jailBlocked: true,
  },
  {
    id: "jail",
    name: "!jail",
    aliases: ["status"],
    module: "economy",
    short: "Checks your sentence and puts a Pay Bail button in front of you. Use it.",
    usage: "!jail",
    examples: ["!jail"],
    keyNumbers: [
      { label: "Default fine", value: "1,000" },
      { label: "Default sentence", value: "10 min" },
    ],
    interactive: true,
  },
  {
    id: "bail",
    name: "!bail",
    aliases: ["release", "paybail", "pay-bail"],
    module: "economy",
    short: "Pays your way out of a cell before the sentence runs its course.",
    usage: "!bail",
    examples: ["!bail"],
    keyNumbers: [{ label: "Default fine", value: "1,000" }],
  },
  {
    id: "daily",
    name: "!daily",
    aliases: [],
    module: "economy",
    short: "A free, untaxed drop every day. Missing it is just leaving money on the table.",
    usage: "!daily",
    examples: ["!daily"],
    cooldown: "24 h",
    keyNumbers: [{ label: "Reward", value: "100,000" }],
    jailBlocked: true,
  },
  {
    id: "weekly",
    name: "!weekly",
    aliases: [],
    module: "economy",
    short:
      "A bigger drop once a week — taxed, but still the best free money in the game.",
    usage: "!weekly",
    examples: ["!weekly"],
    cooldown: "7 days",
    keyNumbers: [
      { label: "Reward", value: "800,000" },
      { label: "Income tax", value: "8%" },
    ],
    jailBlocked: true,
  },
  {
    id: "monthly",
    name: "!monthly",
    aliases: [],
    module: "economy",
    short:
      "The big one. Once a month, taxed, and worth actually setting a reminder for.",
    usage: "!monthly",
    examples: ["!monthly"],
    cooldown: "30 days",
    keyNumbers: [
      { label: "Reward", value: "4,000,000" },
      { label: "Income tax", value: "8%" },
    ],
    jailBlocked: true,
  },
  {
    id: "vote",
    name: "!vote",
    aliases: [],
    module: "economy",
    short: "Vote for the bot on Top.gg, get paid for the click.",
    usage: "!vote [reminder]",
    args: [
      { name: "reminder", desc: "Toggle a reminder ping for your next vote." },
    ],
    examples: ["!vote", "!vote reminder"],
    cooldown: "12 h",
    keyNumbers: [{ label: "Reward", value: "5,000" }],
  },
  {
    id: "rob",
    name: "!rob",
    aliases: ["steal"],
    module: "economy",
    short: "Steal from another wallet directly. Fails loud, and the fine hurts.",
    usage: "!rob <@user>",
    args: [{ name: "@user", desc: "Your target." }],
    examples: ["!rob @Someone"],
    cooldown: "5 min",
    keyNumbers: [
      { label: "Base success", value: "45% (clamped 5–85%)" },
      { label: "Steal amount", value: "8–20% of victim wallet" },
      { label: "Steal cap", value: "250,000" },
      { label: "Fail penalty", value: "60,000 – 120,000" },
    ],
    jailBlocked: true,
  },
  {
    id: "shop",
    name: "!shop",
    aliases: ["store", "buy", "cockstore", "cock-store", "cs"],
    module: "economy",
    short:
      "Every category under one roof — general goods, hunting gear, cosmetics, and cock supplies.",
    usage: "!shop [category|buy <item>|buy card <item>|sell <item>|inv]",
    args: [
      { name: "category", desc: "general | hunt | job | uni | cock | cosmetics" },
      { name: "buy <item>", desc: "Buy with wallet cash." },
      { name: "buy card <item>", desc: "Buy on credit (confirm buttons)." },
      { name: "sell <item>", desc: "Sell an item back." },
      { name: "inv", desc: "Jump to your inventory." },
    ],
    examples: ["!shop", "!shop hunt", "!buy Rifle"],
    interactive: true,
    jailBlocked: true,
  },
  {
    id: "inventory",
    name: "!inventory",
    aliases: ["inv", "bag", "items"],
    module: "economy",
    short: "Everything you own, sorted by category, with buttons to use it right there.",
    usage: "!inventory [category]",
    args: [{ name: "category", desc: "ALL | HUNT | JOB | UNI | COCK" }],
    examples: ["!inventory", "!inv cock"],
    interactive: true,
  },
  {
    id: "use",
    name: "!use",
    aliases: [],
    module: "economy",
    short: "Burns a consumable or special item — feed, boosts, targeted effects, all of it.",
    usage: "!use <item> [amount] [@user]",
    args: [
      { name: "item", desc: "Item name (or feed shorthand: basic/protein/champion)." },
      { name: "amount", desc: "Optional quantity." },
      { name: "@user", desc: "Optional target for items that need one." },
    ],
    examples: ["!use protein 3", "!use Soul Ledger @Someone"],
  },
  {
    id: "equip",
    name: "!equip",
    aliases: [],
    module: "economy",
    short: "Gears up your chicken — weapon, armor, or accessory, one slot at a time.",
    usage: "!equip <item>",
    args: [{ name: "item", desc: "The gear to equip." }],
    examples: ["!equip Wolf Fang Dagger"],
  },
  {
    id: "iteminfo",
    name: "!iteminfo",
    aliases: ["item-info", "item"],
    module: "economy",
    short: "The full spec sheet on any item — price, effect, no surprises after purchase.",
    usage: "!iteminfo <item>",
    args: [{ name: "item", desc: "Item to inspect." }],
    examples: ["!iteminfo Crown of Greed"],
  },
  {
    id: "bank",
    name: "!bank",
    aliases: [],
    module: "economy",
    short:
      "Your bank dashboard — savings, fixed & recurring deposits, and the door to credit cards.",
    usage:
      "!bank [fd <amount> <days> | rd <amount> <days> | collect | investments | cards]",
    args: [
      { name: "fd <amount> <days>", desc: "Open a fixed deposit (10% APR)." },
      { name: "rd <amount> <days>", desc: "Open a recurring deposit (8% APR)." },
      { name: "collect", desc: "Collect matured investments." },
      { name: "investments", desc: "List your active FDs and RDs." },
      { name: "cards", desc: "Open the credit cards hub." },
    ],
    examples: ["!bank", "!bank fd 500000 7", "!bank cards"],
    keyNumbers: [
      { label: "Fixed deposit", value: "10% APR" },
      { label: "Recurring deposit", value: "8% APR" },
    ],
    interactive: true,
    jailBlocked: true,
  },
  {
    id: "card",
    name: "!card",
    aliases: ["creditcard", "credit-card"],
    module: "economy",
    short:
      "Manages your Fortuna Card — issue, pay it down, take a cash advance, upgrade, close.",
    usage: "!card [issue|pay <amount>|withdraw <amount>|upgrade|close]",
    args: [
      { name: "issue", desc: "Apply for a card if you qualify." },
      { name: "pay <amount>", desc: "Pay down your balance from your wallet." },
      { name: "withdraw <amount>", desc: "Cash advance against your credit limit." },
      { name: "upgrade", desc: "Move to a higher tier (needs <50% utilization)." },
      { name: "close", desc: "Close the card (balance must be zero)." },
    ],
    examples: ["!card", "!card pay 100000", "!card upgrade"],
    interactive: true,
    jailBlocked: true,
  },
  {
    id: "mycards",
    name: "!mycards",
    aliases: ["my cards", "my-cards", "mycard"],
    module: "economy",
    short:
      "The full card dashboard — balance, due date, transaction history, pay buttons.",
    usage: "!mycards",
    examples: ["!mycards"],
    interactive: true,
  },
  {
    id: "credit",
    name: "!credit",
    aliases: ["score"],
    module: "economy",
    short:
      "Your credit score, your best eligible tier, and the card you're already carrying.",
    usage: "!credit",
    examples: ["!credit"],
    keyNumbers: [{ label: "Score range", value: "300 – 850" }],
  },
  {
    id: "stock",
    name: "!stock",
    aliases: ["stocks", "stock-market", "stockmarket"],
    module: "economy",
    short:
      "One global market, real volatility, prices that move whether you're watching or not.",
    usage: "!stock [buy <symbol> <qty>|sell <symbol> <qty>|portfolio|news]",
    args: [
      { name: "buy <symbol> <qty>", desc: "Buy shares." },
      { name: "sell <symbol> <qty>", desc: "Sell shares." },
      { name: "portfolio", desc: "View your holdings." },
      { name: "news", desc: "Read the latest market rumors." },
    ],
    examples: ["!stock", "!stock buy ACME 10", "!stock news"],
    keyNumbers: [{ label: "Price ticks", value: "every 30 min" }],
    jailBlocked: true,
  },
  {
    id: "my-stocks",
    name: "!my-stocks",
    aliases: ["mystocks", "my-stock", "mystock", "stock-portfolio"],
    module: "economy",
    short: "Your positions, your profit and loss, no spin.",
    usage: "!my-stocks",
    examples: ["!my-stocks"],
  },
  {
    id: "market",
    name: "!market",
    aliases: ["bm", "black-market", "blackmarket"],
    module: "economy",
    short:
      "Player-to-player trading floor — list, browse, and move animal parts and rare goods.",
    usage: "!market",
    examples: ["!market"],
    keyNumbers: [
      { label: "Buyer fee", value: "5%" },
      { label: "Seller fee", value: "10%" },
      { label: "Listing expiry", value: "7 days" },
      { label: "Listing cap", value: "5 per user" },
    ],
    interactive: true,
    jailBlocked: true,
  },
  {
    id: "leaderboard",
    name: "!leaderboard",
    aliases: ["lb", "top", "rich", "lb-wallet", "lbwallet", "cashlb"],
    module: "economy",
    short: "The server's net worth ranking, with toggles for wallet cash and top earners.",
    usage: "!leaderboard [cash|work]",
    args: [
      { name: "cash", desc: "Show the wallet-only board." },
      { name: "work", desc: "Show the top employees board." },
    ],
    examples: ["!leaderboard", "!leaderboard cash", "!lb-wallet"],
    interactive: true,
  },
  {
    id: "profile",
    name: "!profile",
    aliases: ["p", "me", "userinfo"],
    module: "economy",
    short:
      "Your full dossier — wealth, career, education, relationship, cosmetics — one command.",
    usage: "!profile [@user]",
    args: [{ name: "@user", desc: "View someone else's profile." }],
    examples: ["!profile", "!profile @Someone"],
    interactive: true,
  },
  {
    id: "properties",
    name: "!properties",
    aliases: ["realestate", "estate"],
    module: "economy",
    short: "Browse buyable real estate — passive rent income for players who think long-term.",
    usage: "!properties [collect|mine]",
    args: [
      { name: "collect", desc: "Collect rent from every property you own." },
      { name: "mine", desc: "List the properties you own." },
    ],
    examples: ["!properties", "!properties mine"],
    interactive: true,
  },
  {
    id: "buy-property",
    name: "!buy-property",
    aliases: ["buyproperty", "buyprop"],
    module: "economy",
    short: "Locks in a property purchase by key. Rent starts accruing the moment it's yours.",
    usage: "!buy-property <key>",
    args: [{ name: "key", desc: "The property's listing key." }],
    examples: ["!buy-property downtown-flat"],
  },
  {
    id: "sell-property",
    name: "!sell-property",
    aliases: ["sellproperty", "sellprop"],
    module: "economy",
    short: "Sells a property you own back off your hands.",
    usage: "!sell-property <key>",
    args: [{ name: "key", desc: "The property's listing key." }],
    examples: ["!sell-property downtown-flat"],
  },
  {
    id: "my-properties",
    name: "!my-properties",
    aliases: ["myproperties", "myprops", "portfolio"],
    module: "economy",
    short: "Your real estate holdings, all in one list.",
    usage: "!my-properties",
    examples: ["!my-properties"],
  },
  {
    id: "collect-rent",
    name: "!collect-rent",
    aliases: ["collectrent", "rent"],
    module: "economy",
    short: "Sweeps accumulated rent from every property you own straight into your wallet.",
    usage: "!collect-rent",
    examples: ["!collect-rent"],
  },

  // ── casino ─────────────────────────────────────────────────
  {
    id: "coinflip",
    name: "!coinflip",
    aliases: [],
    module: "casino",
    short: "Heads or tails, 2x or nothing. The simplest bet in the building.",
    usage: "!coinflip <amount> [h|t]",
    args: [
      { name: "amount", desc: "Wallet amount to stake (10,000 – 500,000)." },
      { name: "h|t", desc: "Optional call — heads or tails — or use the buttons." },
    ],
    examples: ["!coinflip 20000 h", "!coinflip 20000"],
    cooldown: "20 min (casino cooldown, per game)",
    keyNumbers: [
      { label: "Win pays", value: "2x" },
      { label: "Bets", value: "10,000 – 500,000" },
    ],
    interactive: true,
    jailBlocked: true,
  },
  {
    id: "slots",
    name: "!slots",
    aliases: ["slot"],
    module: "casino",
    short: "Three reels, luck-adjusted odds. The jackpot symbol is rare for a reason.",
    usage: "!slots <amount>",
    args: [{ name: "amount", desc: "Wallet amount to stake (10,000 – 750,000)." }],
    examples: ["!slots 50000"],
    cooldown: "25 min (casino cooldown, per game)",
    keyNumbers: [
      { label: "7️⃣ pays", value: "20x (0.5% odds)" },
      { label: "💎 pays", value: "10x (1.5% odds)" },
      { label: "🔔 pays", value: "5x (4% odds)" },
      { label: "Grapes/Melon pays", value: "3x (7% odds)" },
      { label: "Cherry/Banana pays", value: "2x (15% odds)" },
      { label: "Bets", value: "10,000 – 750,000" },
    ],
    jailBlocked: true,
  },
  {
    id: "blackjack",
    name: "!blackjack",
    aliases: ["bj"],
    module: "casino",
    short: "Play a full hand against the dealer. Dealer hits to 17. Try not to cry.",
    usage: "!blackjack <bet>",
    args: [
      { name: "bet", desc: "Wallet amount to stake (10,000 – 1,000,000)." },
    ],
    examples: ["!blackjack 250000", "!bj 10000"],
    cooldown: "30 min (casino cooldown, per game)",
    keyNumbers: [
      { label: "Blackjack pays", value: "2.5x" },
      { label: "Win pays", value: "2x" },
      { label: "Push", value: "bet returned" },
      { label: "Bets", value: "10,000 – 1,000,000" },
    ],
    interactive: true,
    jailBlocked: true,
  },
  {
    id: "bet",
    name: "!bet",
    aliases: ["roulette", "roul"],
    module: "casino",
    short: "Bet on a number, color, dozen, or range. The wheel doesn't care about your system.",
    usage: "!bet <amount> <space>",
    args: [
      { name: "amount", desc: "Wallet amount to stake (10,000 – 1,000,000)." },
      { name: "space", desc: "Number, color, range, dozen, or column — e.g. red, 17, 1-12." },
    ],
    examples: ["!bet 50000 red", "!bet 50000 17"],
    cooldown: "30 min (casino cooldown, per game)",
    keyNumbers: [
      { label: "Single number", value: "x36" },
      { label: "Dozens/columns", value: "x3" },
      { label: "Halves/odd-even/colors", value: "x2" },
      { label: "Bets", value: "10,000 – 1,000,000" },
    ],
    jailBlocked: true,
  },
  {
    id: "roulette-guide",
    name: "!roulette-guide",
    aliases: ["roul-guide", "rouletteguide", "roulguide"],
    module: "casino",
    short:
      "Opens the roulette payout menu so you know what x36 feels like before you chase it.",
    usage: "!roulette-guide",
    examples: ["!roulette-guide"],
    keyNumbers: [
      { label: "Single number", value: "x36" },
      { label: "Dozens/columns", value: "x3" },
      { label: "Halves/odd-even/colors", value: "x2" },
    ],
  },
  {
    id: "rr",
    name: "!rr",
    aliases: ["russianroulette", "russian-roulette"],
    module: "casino",
    short: "Multiplayer lobby, one bullet, up to six players. Loser eats the pot's absence.",
    usage: "!rr [start <amount>|join|force]",
    args: [
      { name: "start <amount>", desc: "Open a new lobby at a given stake." },
      { name: "join", desc: "Join the open lobby." },
      { name: "force", desc: "Force-start before the timer runs out." },
    ],
    examples: ["!rr start 100000", "!rr join"],
    keyNumbers: [
      { label: "Players", value: "2 – 6" },
      { label: "Lobby timer", value: "60 sec" },
      { label: "Bets", value: "10,000 – 750,000" },
    ],
    interactive: true,
  },
  {
    id: "cockfight",
    name: "!cockfight",
    aliases: ["cock-fight", "cf"],
    module: "casino",
    short: "Stat-based cockfighting with side bets and a betting window. Raise a winner first.",
    usage: "!cockfight <amount>",
    args: [{ name: "amount", desc: "Wallet amount to stake (10,000 – 1,000,000)." }],
    examples: ["!cockfight 100000"],
    cooldown: "45 min (casino cooldown, per game)",
    keyNumbers: [
      { label: "Bet window", value: "60 sec" },
      { label: "Bets", value: "10,000 – 1,000,000" },
    ],
    interactive: true,
    jailBlocked: true,
  },
  {
    id: "chicken",
    name: "!chicken",
    aliases: ["cock"],
    module: "casino",
    short: "Manage your fighting chicken — name it, train it, check the top ranks.",
    usage: "!chicken [name <name>|train|top|traits]",
    args: [
      { name: "name <name>", desc: "Rename your chicken." },
      { name: "train", desc: "Train it for combat stats." },
      { name: "top", desc: "See the leaderboard." },
      { name: "traits", desc: "View its stats and traits." },
    ],
    examples: ["!chicken", "!chicken train"],
    jailBlocked: true,
  },
  {
    id: "feed",
    name: "!feed",
    aliases: [],
    module: "casino",
    short: "Feeds your chicken to bump its combat stats before the next fight.",
    usage: "!feed",
    examples: ["!feed"],
  },
  {
    id: "hunt",
    name: "!hunt",
    aliases: [],
    module: "casino",
    short: "Take your rifle out and hunt animals for the zoo and the market.",
    usage: "!hunt [craft]",
    args: [{ name: "craft", desc: "Open the crafting payload." }],
    examples: ["!hunt", "!hunt craft"],
    interactive: true,
  },
  {
    id: "zoo",
    name: "!zoo",
    aliases: ["myzoo", "my-zoo"],
    module: "casino",
    short: "Your captured animals on display — capacity and income scale with rarity.",
    usage: "!zoo",
    examples: ["!zoo"],
    interactive: true,
  },

  // ── life ───────────────────────────────────────────────────
  {
    id: "work",
    name: "!work",
    aliases: ["job", "myjob"],
    module: "life",
    short: "Clock a shift at your job. Pay is real, and so is the stress.",
    usage: "!work",
    examples: ["!work"],
    keyNumbers: [
      { label: "Income tax", value: "8%" },
      { label: "Job pay range", value: "30,000 – 450,000 per shift" },
    ],
    interactive: true,
    jailBlocked: true,
  },
  {
    id: "jobs",
    name: "!jobs",
    aliases: ["careers", "joblist"],
    module: "life",
    short: "Browse every job you're eligible for, gated by degree and career tier.",
    usage: "!jobs",
    examples: ["!jobs"],
  },
  {
    id: "apply",
    name: "!apply",
    aliases: [],
    module: "life",
    short: "Applies for a job by name. Meet the requirements or don't bother.",
    usage: "!apply <job>",
    args: [{ name: "job", desc: "The job title to apply for." }],
    examples: ["!apply Waiter"],
  },
  {
    id: "career",
    name: "!career",
    aliases: ["mycareer"],
    module: "life",
    short: "Your career progression and the promotion path ahead of you.",
    usage: "!career",
    examples: ["!career"],
  },
  {
    id: "relax",
    name: "!relax",
    aliases: ["chill"],
    module: "life",
    short: "Buy down job and education stress before it starts costing you shifts.",
    usage: "!relax",
    examples: ["!relax"],
    keyNumbers: [
      { label: "Quick Break", value: "25,000 (-8 job / -8 edu stress)" },
      { label: "Gym Session", value: "75,000 (-20 / -15 stress)" },
      { label: "Meditation Retreat", value: "150,000 (-35 / -35 stress)" },
      { label: "Weekend Getaway", value: "350,000 (-75 / -60 stress)" },
    ],
    interactive: true,
  },
  {
    id: "education",
    name: "!education",
    aliases: ["uni", "university", "edu", "school"],
    module: "life",
    short: "Your education dashboard — current program's XP bar and scholarship milestones.",
    usage: "!education",
    examples: ["!education"],
  },
  {
    id: "degrees",
    name: "!degrees",
    aliases: ["mydegrees", "degree"],
    module: "life",
    short: "Every degree you've earned so far, listed out.",
    usage: "!degrees",
    examples: ["!degrees"],
  },
  {
    id: "enroll",
    name: "!enroll",
    aliases: [],
    module: "life",
    short: "Enrolls you in a degree program by name. Tuition due up front.",
    usage: "!enroll <degree>",
    args: [{ name: "degree", desc: "The degree name to enroll in." }],
    examples: ["!enroll BS Computer Science"],
    keyNumbers: [
      { label: "High School Diploma", value: "150,000" },
      { label: "Trade License", value: "300,000" },
      { label: "BA Fine Arts", value: "900,000" },
      { label: "BS Computer Science", value: "1,200,000" },
      { label: "LLB", value: "2,500,000" },
      { label: "MBBS", value: "4,000,000" },
      { label: "LLM", value: "6,000,000" },
      { label: "MD/PhD", value: "10,000,000" },
    ],
  },
  {
    id: "exam",
    name: "!exam",
    aliases: ["finals"],
    module: "life",
    short: "Take the final exam and graduate — or find out you weren't ready.",
    usage: "!exam",
    examples: ["!exam"],
  },
  {
    id: "study",
    name: "!study",
    aliases: [],
    module: "life",
    short: "A quick study minigame that chips away at your current program's XP bar.",
    usage: "!study",
    examples: ["!study"],
    cooldown: "5 min",
    interactive: true,
  },
  {
    id: "dropout",
    name: "!dropout",
    aliases: [],
    module: "life",
    short: "Walks away from your current program. No refunds.",
    usage: "!dropout",
    examples: ["!dropout"],
  },
  {
    id: "marry",
    name: "!marry",
    aliases: ["propose"],
    module: "life",
    short: "Sends a proposal. If they say yes, the joint vault opens up.",
    usage: "!marry <@user>",
    args: [{ name: "@user", desc: "Who you're proposing to." }],
    examples: ["!marry @Someone"],
    keyNumbers: [{ label: "Cost", value: "free" }],
  },
  {
    id: "divorce",
    name: "!divorce",
    aliases: [],
    module: "life",
    short: "Ends the marriage. Currently costs nothing, which says something.",
    usage: "!divorce",
    examples: ["!divorce"],
    keyNumbers: [{ label: "Cost", value: "free" }],
  },
  {
    id: "family",
    name: "!family",
    aliases: ["spouse", "marriage"],
    module: "life",
    short: "Your relationship dashboard — joint vault, hugs, dates, and the chaos option.",
    usage: "!family [bank|deposit <amt>|withdraw <amt>|hug|kiss|date|chaos|make love]",
    args: [
      { name: "bank", desc: "View the joint vault balance." },
      { name: "deposit <amt>", desc: "Add to the joint vault." },
      { name: "withdraw <amt>", desc: "Take from the joint vault." },
      { name: "hug|kiss|date|chaos", desc: "Affection actions with your spouse." },
    ],
    examples: ["!family", "!family hug", "!family deposit 50000"],
    keyNumbers: [{ label: "Joint vault", value: "shared savings" }],
    interactive: true,
  },
  {
    id: "quests",
    name: "!quests",
    aliases: ["quest", "dailyquest", "missions", "daily-quests", "dailyquests"],
    module: "life",
    short: "Daily quest board with a streak bonus and one free reroll if you hate your tasks.",
    usage: "!quests",
    examples: ["!quests"],
    interactive: true,
  },
];

export function getCommand(id: string): Command | undefined {
  return COMMANDS.find((c) => c.id === id);
}
