import { ItemEffect } from "../services/effectService";

export type ShopCategory = "GENERAL" | "JOB" | "UNI" | "COCK" | "HUNT";

export interface ShopCatalogItem {
  key: string;
  name: string;
  price: number;
  description: string;
  shortDescription: string;
  category: ShopCategory;
  asset?: string;
  consumable: boolean;
  usable: boolean;
  itemType: "CONSUMABLE" | "EQUIPMENT" | "COLLECTIBLE";
  effects: ItemEffect[];
  maxStack?: number;
}

export const SHOP_CATEGORIES: { key: ShopCategory; label: string; emoji: string; emojiKey?: string }[] = [
  { key: "GENERAL", label: "General Store", emoji: "🛒", emojiKey: "fortunes" },
  { key: "JOB",     label: "Job Store",     emoji: "💼" },
  { key: "UNI",     label: "Uni Store",     emoji: "📚" },
  { key: "COCK",    label: "Cock Store",    emoji: "🐔" },
  { key: "HUNT",    label: "Hunt Store",    emoji: "🎯", emojiKey: "rabbit" },
];

export const GENERAL_SHOP_CATALOG: ShopCatalogItem[] = [
  // ── Page 1 ──────────────────────────────────────────────────────────────
  {
    key: "tax_shield",
    name: "Tax Shield",
    price: 10_000,
    description: "A legal loophole sealed inside a Fortuna-grade shield. Activate it to block transfer and market taxes for 1 hour. Best used before trading, moving money, or making expensive market plays.",
    shortDescription: "Blocks taxes for 1 hour.",
    category: "GENERAL",
    asset: "tax_shield",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [
      { type: "CUSTOM_MESSAGE", message: "Tax Shield active! You are exempt from all transaction taxes for 1 hour.", trigger: "USE" },
    ],
  },
  {
    key: "bandage",
    name: "Bandage",
    price: 25_000,
    description: "A quick patch-up for reckless players. Clears one active game cooldown so you can jump back into the action sooner. Simple, cheap, and useful after a bad run.",
    shortDescription: "Clears one active game cooldown.",
    category: "GENERAL",
    asset: "bandage",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [
      { type: "COOLDOWN_REDUCTION", value: 3600, duration: 1, trigger: "USE" },
      { type: "CUSTOM_MESSAGE", message: "Bandage applied! Your game cooldown has been cleared.", trigger: "USE" },
    ],
  },
  {
    key: "counterfeit_kit",
    name: "Counterfeit Kit",
    price: 50_000,
    description: "A suspicious purple kit filled with fake seals, forged slips, and terrible ideas. Boosts your next daily or work income by 25% if used within 2 hours.",
    shortDescription: "Boosts next daily/work income by 25%.",
    category: "GENERAL",
    asset: "couterfeit_kit",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [
      { type: "PAY_MULTIPLIER", value: 0.25, duration: 7200, trigger: "USE" },
      { type: "CUSTOM_MESSAGE", message: "Counterfeit Kit activated! Your next income is boosted by 25% (2hr).", trigger: "USE" },
    ],
  },
  {
    key: "lucky_coin",
    name: "Lucky Coin",
    price: 75_000,
    description: "A gold coin carrying a clover mark and a little bit of dangerous hope. Boosts your next game payout by 50% for 5 minutes. Use it right before gambling or playing a payout game.",
    shortDescription: "Boosts next game payout by 50%.",
    category: "GENERAL",
    asset: "lucky_coin",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [
      { type: "PAY_MULTIPLIER", value: 0.5, duration: 300, trigger: "USE" },
      { type: "CUSTOM_MESSAGE", message: "Lucky Coin activated! Your next game payout is boosted by 50% for 5 minutes.", trigger: "USE" },
    ],
  },
  {
    key: "thief_gloves",
    name: "Thieves Gloves",
    price: 100_000,
    description: "Dark gloves made for quiet hands and bad decisions. Increases robbery earnings by 25% for the next few rob attempts or until the effect expires.",
    shortDescription: "Boosts robbery earnings.",
    category: "GENERAL",
    asset: "thief_gloves",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [
      { type: "PAY_MULTIPLIER", value: 0.25, duration: 21600, trigger: "USE" },
      { type: "CUSTOM_MESSAGE", message: "Thieves Gloves equipped! Your robbery earnings are boosted by 25% for 6 hours.", trigger: "USE" },
    ],
  },
  {
    key: "energy_drink",
    name: "Energy Drink",
    price: 125_000,
    description: "A violent little can of purple caffeine. Reduces your job cooldown by 1 hour, letting grinders squeeze in another shift sooner.",
    shortDescription: "Reduces job cooldown by 1 hour.",
    category: "GENERAL",
    asset: "energy_drink",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [
      { type: "COOLDOWN_REDUCTION", value: 3600, duration: 1, trigger: "USE" },
      { type: "CUSTOM_MESSAGE", message: "Energy Drink consumed! Your job cooldown is reduced by 1 hour.", trigger: "USE" },
    ],
  },
  {
    key: "padlock",
    name: "Padlock",
    price: 175_000,
    description: "A bright lock for people who know their friends too well. Blocks one robbery attempt against you within 24 hours, then breaks after protecting your wallet.",
    shortDescription: "Blocks one robbery attempt.",
    category: "GENERAL",
    asset: "padlock",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [
      { type: "CUSTOM_MESSAGE", message: "Padlock engaged! Your wallet is protected from the next robbery attempt (24hr).", trigger: "USE" },
    ],
  },
  {
    key: "mystery_box",
    name: "Mystery Box",
    price: 250_000,
    description: "A sealed Fortuna crate with a question mark and questionable odds. Open it for a random reward. Most outcomes are modest, but rare pulls can pay much better.",
    shortDescription: "Random reward crate.",
    category: "GENERAL",
    asset: "mystery_box",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [
      { type: "CUSTOM_MESSAGE", message: "Opening Mystery Box...", trigger: "USE" },
    ],
  },
  {
    key: "treasure_map",
    name: "Treasure Map",
    price: 400_000,
    description: "An old map marked with a red cross and too much confidence. Follow it for a treasure roll with higher upside than the Mystery Box, but less predictable results.",
    shortDescription: "Higher-risk treasure reward.",
    category: "GENERAL",
    asset: "treasure_map",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [
      { type: "CUSTOM_MESSAGE", message: "Following the Treasure Map...", trigger: "USE" },
    ],
  },
  // ── Page 2 ──────────────────────────────────────────────────────────────
  {
    key: "loaded_dice_of_ruin",
    name: "Loaded Dice of Ruin",
    price: 350_000,
    description: "A cursed die weighted toward chaos. Roll it once for a chance to win 500K–1.2M, but failure can burn 150K–600K from your wallet. One use only.",
    shortDescription: "Win big or lose hard.",
    category: "GENERAL",
    asset: "loaded_dice_of_ruin",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    maxStack: 1,
    effects: [{ type: "CUSTOM_MESSAGE", message: "Loaded Dice of Ruin activated!", trigger: "USE" }],
  },
  {
    key: "celestial_harp",
    name: "Celestial Harp",
    price: 450_000,
    description: "A golden harp tuned to Fortuna's softer moods. Grants a temporary luck boost for 6 hours, improving your odds slightly across casino, hunt, crime, and defensive rolls. One use only.",
    shortDescription: "Temporary luck boost.",
    category: "GENERAL",
    asset: "celestial_harp",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    maxStack: 1,
    effects: [{ type: "CUSTOM_MESSAGE", message: "Celestial Harp played! Luck boost active for 6 hours.", trigger: "USE" }],
  },
  {
    key: "demonic_harp",
    name: "Demonic Harp",
    price: 600_000,
    description: "A red-stringed harp that plays badly for someone else. Use it on another player to reduce their luck for 6 hours and make them slightly more vulnerable to robbery. One use only.",
    shortDescription: "Curses another player's luck.",
    category: "GENERAL",
    asset: "demonic_harp",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    maxStack: 1,
    effects: [{ type: "CUSTOM_MESSAGE", message: "Demonic Harp played! Target's luck has been cursed.", trigger: "USE" }],
  },
  {
    key: "pandora_box",
    name: "Pandora Box",
    price: 750_000,
    description: "A locked purple box full of rewards, curses, and bad judgment. Opening it can grant money, a buff, a rare item outcome, a curse, or a wallet loss. One use only.",
    shortDescription: "Random chaos outcome.",
    category: "GENERAL",
    asset: "pandora_box",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    maxStack: 1,
    effects: [{ type: "CUSTOM_MESSAGE", message: "Pandora Box opened!", trigger: "USE" }],
  },
  {
    key: "eclipse_mask",
    name: "Eclipse Mask",
    price: 850_000,
    description: "A shadow mask for one dangerous robbery. Boosts your next rob attempt's success chance and loot, but if you fail, the backlash is much harsher. One use only.",
    shortDescription: "Boosts next robbery with backlash risk.",
    category: "GENERAL",
    asset: "eclipse_mask",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    maxStack: 1,
    effects: [{ type: "CUSTOM_MESSAGE", message: "Eclipse Mask equipped! Next robbery is enhanced.", trigger: "USE" }],
  },
  {
    key: "mirror_of_fate",
    name: "Mirror of Fate",
    price: 900_000,
    description: "A polished mirror that refuses to suffer quietly. For 24 hours, it reflects the next targeted curse or negative item back to the attacker, then shatters. One use only.",
    shortDescription: "Reflects one targeted curse.",
    category: "GENERAL",
    asset: "mirror_of_fate",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    maxStack: 1,
    effects: [{ type: "CUSTOM_MESSAGE", message: "Mirror of Fate activated! Next curse will be reflected.", trigger: "USE" }],
  },
  {
    key: "crown_of_greed",
    name: "Crown of Greed",
    price: 1_000_000,
    description: "A jeweled crown that rewards hunger and punishes mistakes. For 1 hour, your income is boosted by 25%, but your losses are also increased by 25%. One use only.",
    shortDescription: "Boosts income and losses.",
    category: "GENERAL",
    asset: "crown_of_greed",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    maxStack: 1,
    effects: [{ type: "CUSTOM_MESSAGE", message: "Crown of Greed worn! Income and losses boosted for 1 hour.", trigger: "USE" }],
  },
  {
    key: "devil_contract",
    name: "Devil Contract",
    price: 1_250_000,
    description: "A signed pact with very small text. Grants an instant payout between 1.8M and 3M, but your next 3 income events are reduced by 20%. One use only.",
    shortDescription: "Instant payout with income penalty.",
    category: "GENERAL",
    asset: "devil_contract",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    maxStack: 1,
    effects: [{ type: "CUSTOM_MESSAGE", message: "Devil Contract signed!", trigger: "USE" }],
  },
  {
    key: "soul_ledger",
    name: "Soul Ledger",
    price: 1_500_000,
    description: "A dark ledger that records financial pain. It watches for your next loss above 300K. After 24 hours, there is a 50% chance to refund that loss at 1.5x, and a 50% chance to refund nothing. One use only.",
    shortDescription: "Gambles on refunding your next big loss.",
    category: "GENERAL",
    asset: "soul_ledger",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    maxStack: 1,
    effects: [{ type: "CUSTOM_MESSAGE", message: "Soul Ledger activated! Watching for your next big loss.", trigger: "USE" }],
  },
];

export const HUNT_SHOP_CATALOG: ShopCatalogItem[] = [
  {
    key: "wooden_rifle",
    name: "Wooden Rifle",
    price: 500_000,
    description: "A basic rifle carved from oak. Slow and limited, but it gets the job done.",
    shortDescription: "Common — 8hr cooldown",
    category: "HUNT",
    asset: "rifle",
    consumable: false,
    usable: false,
    itemType: "EQUIPMENT",
    effects: [],
  },
  {
    key: "iron_rifle",
    name: "Iron Rifle",
    price: 1_500_000,
    description: "A reliable iron-forged rifle. Shoots faster and can bag Uncommon animals.",
    shortDescription: "Common, Uncommon — 6hr cooldown",
    category: "HUNT",
    asset: "iron rifle",
    consumable: false,
    usable: false,
    itemType: "EQUIPMENT",
    effects: [],
  },
  {
    key: "sniper_rifle",
    name: "Sniper Rifle",
    price: 4_000_000,
    description: "A precision sniper rifle capable of taking down Rare targets.",
    shortDescription: "Common, Uncommon, Rare — 4hr cooldown",
    category: "HUNT",
    asset: "sniper riflle",
    consumable: false,
    usable: false,
    itemType: "EQUIPMENT",
    effects: [],
  },
  {
    key: "legendary_rifle",
    name: "Legendary Rifle",
    price: 12_000_000,
    description: "A mythical rifle said to be forged from dragon steel. A chance at Legendary beasts.",
    shortDescription: "Common, Uncommon, Rare, Legendary — 2hr cooldown",
    category: "HUNT",
    asset: "rifle",
    consumable: false,
    usable: false,
    itemType: "EQUIPMENT",
    effects: [],
  },
  {
    key: "hunting_permit",
    name: "Hunting Permit",
    price: 200_000,
    description: "An official hunting permit required to access restricted hunting zones. One-time purchase.",
    shortDescription: "Access restricted hunting areas",
    category: "HUNT",
    asset: "hunting permit",
    consumable: false,
    usable: false,
    itemType: "COLLECTIBLE",
    effects: [],
  },
  {
    key: "bait_box",
    name: "Bait Box",
    price: 750_000,
    description: "A box of premium bait that lures more animals per hunt. Guarantees at least 2 animals on your next hunt.",
    shortDescription: "Min 2 animals on next hunt",
    category: "HUNT",
    asset: "bait box",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [
      { type: "CUSTOM_MESSAGE", message: "🎣 **Bait Box set!** Your next hunt will attract at least 2 animals.", trigger: "USE" },
    ],
  },
  {
    key: "camouflage_kit",
    name: "Camouflage Kit",
    price: 1_200_000,
    description: "Blend into the wilderness and get the drop on Rare+ animals. Boosts Rare and Legendary catch rates by 25% for your next hunt.",
    shortDescription: "+25% Rare/Legendary chance (1 hunt)",
    category: "HUNT",
    asset: "camouflage kit",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [
      { type: "CUSTOM_MESSAGE", message: "🫱 **Camouflage Kit activated!** Rare+ catch rates boosted for your next hunt.", trigger: "USE" },
    ],
  },
];

export const SHOP_CATALOG: ShopCatalogItem[] = [
  ...GENERAL_SHOP_CATALOG,
  ...HUNT_SHOP_CATALOG,
];

export function getCatalogByCategory(category: ShopCategory): ShopCatalogItem[] {
  return SHOP_CATALOG.filter(item => item.category === category);
}

export function getCatalogItem(key: string): ShopCatalogItem | undefined {
  return SHOP_CATALOG.find(item => item.key === key);
}
