import { ItemEffect } from "../services/effectService";

export type ShopCategory = "GENERAL" | "JOB" | "UNI" | "COCK" | "HUNT";

export interface ShopCatalogItem {
  key: string;
  name: string;
  price: number;
  description: string;
  shortDescription: string;
  category: ShopCategory;
  asset?: string;
  consumable: boolean;
  usable: boolean;
  itemType: "CONSUMABLE" | "EQUIPMENT" | "COLLECTIBLE";
  effects: ItemEffect[];
  maxStack?: number;
  creditBlocked?: boolean;
}

export const SHOP_CATEGORIES: { key: ShopCategory; label: string; emoji: string; emojiKey?: string }[] = [
  { key: "GENERAL", label: "General Store", emoji: "🛒", emojiKey: "fortunes" },
  { key: "JOB",     label: "Job Store",     emoji: "💼" },
  { key: "UNI",     label: "Uni Store",     emoji: "📚" },
  { key: "COCK",    label: "Cock Store",    emoji: "🐔" },
  { key: "HUNT",    label: "Hunt Store",    emoji: "🎯", emojiKey: "rabbit" },
];

export const GENERAL_SHOP_CATALOG: ShopCatalogItem[] = [
  // ── Page 1 ──────────────────────────────────────────────────────────────
  {
    key: "tax_shield",
    name: "Tax Shield",
    price: 10_000,
    description: "A legal loophole sealed inside a Fortuna-grade shield. Activate it to block transfer and market taxes for 1 hour. Best used before trading, moving money, or making expensive market plays.",
    shortDescription: "Blocks taxes for 1 hour.",
    category: "GENERAL",
    asset: "tax_shield",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [
      { type: "CUSTOM_MESSAGE", message: "Tax Shield active! You are exempt from all transaction taxes for 1 hour.", trigger: "USE" },
    ],
  },
  {
    key: "bandage",
    name: "Bandage",
    price: 25_000,
    description: "A quick patch-up for reckless players. Clears one active game cooldown so you can jump back into the action sooner. Simple, cheap, and useful after a bad run.",
    shortDescription: "Clears your most recent casino game cooldown.",
    category: "GENERAL",
    asset: "bandage",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [
      { type: "COOLDOWN_REDUCTION", value: 3600, duration: 1, trigger: "USE" },
      { type: "CUSTOM_MESSAGE", message: "Bandage applied! Your game cooldown has been cleared.", trigger: "USE" },
    ],
  },
  {
    key: "counterfeit_kit",
    name: "Counterfeit Kit",
    price: 50_000,
    description: "A suspicious purple kit filled with fake seals, forged slips, and terrible ideas. Boosts your next daily or work income by 25% if used within 2 hours.",
    shortDescription: "Boosts next daily/work income by 25%.",
    category: "GENERAL",
    asset: "couterfeit_kit",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [
      { type: "PAY_MULTIPLIER", value: 0.25, duration: 7200, trigger: "USE" },
      { type: "CUSTOM_MESSAGE", message: "Counterfeit Kit activated! Your next income is boosted by 25% (2hr).", trigger: "USE" },
    ],
  },
  {
    key: "lucky_coin",
    name: "Lucky Coin",
    price: 75_000,
    description: "A gold coin carrying a clover mark and a little bit of dangerous hope. Boosts your next game payout by 50% for 5 minutes. Use it right before gambling or playing a payout game.",
    shortDescription: "Boosts next game payout by 50%.",
    category: "GENERAL",
    asset: "lucky_coin",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [
      { type: "PAY_MULTIPLIER", value: 0.5, duration: 300, trigger: "USE" },
      { type: "CUSTOM_MESSAGE", message: "Lucky Coin activated! Your next game payout is boosted by 50% for 5 minutes.", trigger: "USE" },
    ],
  },
  {
    key: "thief_gloves",
    name: "Thieves Gloves",
    price: 100_000,
    description: "Dark gloves made for quiet hands and bad decisions. Increases robbery earnings by 25% for the next few rob attempts or until the effect expires.",
    shortDescription: "Boosts robbery earnings.",
    category: "GENERAL",
    asset: "thief_gloves",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [
      { type: "PAY_MULTIPLIER", value: 0.25, duration: 21600, trigger: "USE" },
      { type: "CUSTOM_MESSAGE", message: "Thieves Gloves equipped! Your robbery earnings are boosted by 25% for 6 hours.", trigger: "USE" },
    ],
  },
  {
    key: "energy_drink",
    name: "Energy Drink",
    price: 125_000,
    description: "A violent little can of purple caffeine. Reduces your job cooldown by 1 hour, letting grinders squeeze in another shift sooner.",
    shortDescription: "Reduces job cooldown by 1 hour.",
    category: "GENERAL",
    asset: "energy_drink",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [
      { type: "COOLDOWN_REDUCTION", value: 3600, duration: 1, trigger: "USE" },
      { type: "CUSTOM_MESSAGE", message: "Energy Drink consumed! Your job cooldown is reduced by 1 hour.", trigger: "USE" },
    ],
  },
  {
    key: "padlock",
    name: "Padlock",
    price: 175_000,
    description: "A bright lock for people who know their friends too well. Blocks one robbery attempt against you within 24 hours, then breaks after protecting your wallet.",
    shortDescription: "Blocks one robbery attempt.",
    category: "GENERAL",
    asset: "padlock",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [
      { type: "CUSTOM_MESSAGE", message: "Padlock engaged! Your wallet is protected from the next robbery attempt (24hr).", trigger: "USE" },
    ],
  },
  {
    key: "mystery_box",
    name: "Mystery Box",
    price: 250_000,
    description: "A sealed Fortuna crate with a question mark and questionable odds. Open it for a random reward. Most outcomes are modest, but rare pulls can pay much better.",
    shortDescription: "Random reward crate.",
    category: "GENERAL",
    asset: "mystery_box",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    creditBlocked: true,
    effects: [
      { type: "CUSTOM_MESSAGE", message: "Opening Mystery Box...", trigger: "USE" },
    ],
  },
  {
    key: "treasure_map",
    name: "Treasure Map",
    price: 400_000,
    description: "An old map marked with a red cross and too much confidence. Follow it for a treasure roll with higher upside than the Mystery Box, but less predictable results.",
    shortDescription: "Higher-risk treasure reward.",
    category: "GENERAL",
    asset: "treasure_map",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    creditBlocked: true,
    effects: [
      { type: "CUSTOM_MESSAGE", message: "Following the Treasure Map...", trigger: "USE" },
    ],
  },
  // ── Page 2 ──────────────────────────────────────────────────────────────
  {
    key: "loaded_dice_of_ruin",
    name: "Loaded Dice of Ruin",
    price: 350_000,
    description: "A cursed die weighted toward chaos. Roll it once for a chance to win 500K–1.2M, but failure can burn 150K–600K from your wallet. One use only.",
    shortDescription: "Win big or lose hard.",
    category: "GENERAL",
    asset: "loaded_dice_of_ruin",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    maxStack: 1,
    effects: [{ type: "CUSTOM_MESSAGE", message: "Loaded Dice of Ruin activated!", trigger: "USE" }],
  },
  {
    key: "celestial_harp",
    name: "Celestial Harp",
    price: 450_000,
    description: "A golden harp tuned to Fortuna's softer moods. Grants a temporary luck boost for 6 hours, improving your odds slightly across casino, hunt, crime, and defensive rolls. One use only.",
    shortDescription: "Temporary luck boost.",
    category: "GENERAL",
    asset: "celestial_harp",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    maxStack: 1,
    effects: [{ type: "CUSTOM_MESSAGE", message: "Celestial Harp played! Luck boost active for 6 hours.", trigger: "USE" }],
  },
  {
    key: "demonic_harp",
    name: "Demonic Harp",
    price: 600_000,
    description: "A red-stringed harp that plays badly for someone else. Use it on another player to reduce their luck for 6 hours and make them slightly more vulnerable to robbery. One use only.",
    shortDescription: "Curses another player's luck.",
    category: "GENERAL",
    asset: "demonic_harp",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    maxStack: 1,
    effects: [{ type: "CUSTOM_MESSAGE", message: "Demonic Harp played! Target's luck has been cursed.", trigger: "USE" }],
  },
  {
    key: "pandora_box",
    name: "Pandora Box",
    price: 750_000,
    description: "A locked purple box full of rewards, curses, and bad judgment. Opening it can grant money, a buff, a rare item outcome, a curse, or a wallet loss. One use only.",
    shortDescription: "Random chaos outcome.",
    category: "GENERAL",
    asset: "pandora_box",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    creditBlocked: true,
    maxStack: 1,
    effects: [{ type: "CUSTOM_MESSAGE", message: "Pandora Box opened!", trigger: "USE" }],
  },
  {
    key: "eclipse_mask",
    name: "Eclipse Mask",
    price: 850_000,
    description: "A shadow mask for one dangerous robbery. Boosts your next rob attempt's success chance and loot, but if you fail, the backlash is much harsher. One use only.",
    shortDescription: "Boosts next robbery with backlash risk.",
    category: "GENERAL",
    asset: "eclipse_mask",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    maxStack: 1,
    effects: [{ type: "CUSTOM_MESSAGE", message: "Eclipse Mask equipped! Next robbery is enhanced.", trigger: "USE" }],
  },
  {
    key: "mirror_of_fate",
    name: "Mirror of Fate",
    price: 900_000,
    description: "A polished mirror that refuses to suffer quietly. For 24 hours, it reflects the next targeted curse or negative item back to the attacker, then shatters. One use only.",
    shortDescription: "Reflects one targeted curse.",
    category: "GENERAL",
    asset: "mirror_of_fate",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    maxStack: 1,
    effects: [{ type: "CUSTOM_MESSAGE", message: "Mirror of Fate activated! Next curse will be reflected.", trigger: "USE" }],
  },
  {
    key: "crown_of_greed",
    name: "Crown of Greed",
    price: 1_000_000,
    description: "A jeweled crown that rewards hunger and punishes mistakes. For 1 hour, your income is boosted by 25%, but your losses are also increased by 25%. One use only.",
    shortDescription: "Boosts income and losses.",
    category: "GENERAL",
    asset: "crown_of_greed",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    maxStack: 1,
    effects: [{ type: "CUSTOM_MESSAGE", message: "Crown of Greed worn! Income and losses boosted for 1 hour.", trigger: "USE" }],
  },
  {
    key: "devil_contract",
    name: "Devil Contract",
    price: 1_250_000,
    description: "A signed pact with very small text. Grants an instant payout between 1.8M and 3M, but your next 3 income events are reduced by 20%. One use only.",
    shortDescription: "Instant payout with income penalty.",
    category: "GENERAL",
    asset: "devil_contract",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    maxStack: 1,
    effects: [{ type: "CUSTOM_MESSAGE", message: "Devil Contract signed!", trigger: "USE" }],
  },
  {
    key: "soul_ledger",
    name: "Soul Ledger",
    price: 1_500_000,
    description: "A dark ledger that records financial pain. It watches for your next loss above 300K. After 24 hours, there is a 50% chance to refund that loss at 1.5x, and a 50% chance to refund nothing. One use only.",
    shortDescription: "Gambles on refunding your next big loss.",
    category: "GENERAL",
    asset: "soul_ledger",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    maxStack: 1,
    effects: [{ type: "CUSTOM_MESSAGE", message: "Soul Ledger activated! Watching for your next big loss.", trigger: "USE" }],
  },
];

export const HUNT_SHOP_CATALOG: ShopCatalogItem[] = [
  {
    key: "hunting_permit",
    name: "Hunting Permit",
    price: 200_000,
    description: "An official permit stamped by Fortuna's hunting office. Unlocks restricted hunting zones and advanced hunt features. A one-time purchase for serious hunters.",
    shortDescription: "Unlocks advanced hunting.",
    category: "HUNT",
    asset: "hunting permit",
    consumable: false,
    usable: false,
    itemType: "COLLECTIBLE",
    effects: [],
  },
  {
    key: "wooden_rifle",
    name: "Wooden Rifle",
    price: 500_000,
    description: "A basic rifle carved from oak and stubborn optimism. Catches Common animals only and has an 8 hour hunt cooldown. The starter weapon for new hunters.",
    shortDescription: "Common animals, 8h cooldown.",
    category: "HUNT",
    asset: "rifle",
    consumable: false,
    usable: false,
    itemType: "EQUIPMENT",
    effects: [],
  },
  {
    key: "echo_whistle",
    name: "Echo Whistle",
    price: 600_000,
    description: "A silver whistle that calls back whatever the forest almost let escape. After your next hunt, it has a 35% chance to attract one extra animal matching the rarity of your best catch. One use only.",
    shortDescription: "Chance to echo your best catch.",
    category: "HUNT",
    asset: "echo_whistle",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    maxStack: 1,
    effects: [
      { type: "CUSTOM_MESSAGE", message: "Echo Whistle activated! Watching for your next hunt.", trigger: "USE" },
    ],
  },
  {
    key: "bait_box",
    name: "Bait Box",
    price: 750_000,
    description: "A box of premium bait with a smell best left undescribed. Guarantees at least 2 animals on your next hunt. One use only.",
    shortDescription: "Guarantees at least 2 animals.",
    category: "HUNT",
    asset: "bait box",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    maxStack: 1,
    effects: [
      { type: "CUSTOM_MESSAGE", message: "Bait Box set! Your next hunt will attract at least 2 animals.", trigger: "USE" },
    ],
  },
  {
    key: "camouflage_kit",
    name: "Camouflage Kit",
    price: 1_200_000,
    description: "A full camouflage setup for hunters who prefer the forest not knowing they exist. Boosts Rare and Legendary catch chances on your next hunt. One use only.",
    shortDescription: "Boosts Rare+ catch chance.",
    category: "HUNT",
    asset: "camouflage kit",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    maxStack: 1,
    effects: [
      { type: "CUSTOM_MESSAGE", message: "Camouflage Kit activated! Rare+ catch rates boosted for your next hunt.", trigger: "USE" },
    ],
  },
  {
    key: "iron_rifle",
    name: "Iron Rifle",
    price: 1_500_000,
    description: "A reliable iron-forged rifle with cleaner aim and better range. Can catch Common and Uncommon animals with a 6 hour hunt cooldown.",
    shortDescription: "Common/Uncommon, 6h cooldown.",
    category: "HUNT",
    asset: "iron rifle",
    consumable: false,
    usable: false,
    itemType: "EQUIPMENT",
    effects: [],
  },
  {
    key: "hunters_compass",
    name: "Hunter's Compass",
    price: 2_250_000,
    description: "A compass that points toward opportunity instead of north. Once per day, lets the hunter choose between safer Common/Uncommon odds or a riskier Rare+ hunting path.",
    shortDescription: "Choose safer or riskier hunt path.",
    category: "HUNT",
    asset: "hunters_compass",
    consumable: false,
    usable: false,
    itemType: "EQUIPMENT",
    effects: [],
  },
  {
    key: "sniper_rifle",
    name: "Sniper Rifle",
    price: 4_000_000,
    description: "A precision rifle for patient hunters and expensive mistakes. Can catch Common, Uncommon, and Rare animals with a 4 hour hunt cooldown.",
    shortDescription: "Can catch Rare animals, 4h cooldown.",
    category: "HUNT",
    asset: "sniper riflle",
    consumable: false,
    usable: false,
    itemType: "EQUIPMENT",
    effects: [],
  },
  {
    key: "legendary_rifle",
    name: "Legendary Rifle",
    price: 12_000_000,
    description: "A mythical rifle built for hunters chasing stories, not animals. Can catch Common, Uncommon, Rare, and Legendary animals with a 2 hour hunt cooldown.",
    shortDescription: "Can catch Legendary animals, 2h cooldown.",
    category: "HUNT",
    asset: "rifle",
    consumable: false,
    usable: false,
    itemType: "EQUIPMENT",
    effects: [],
  },
];

export const JOB_SHOP_CATALOG: ShopCatalogItem[] = [
  {
    key: "work_laptop",
    name: "Work Laptop",
    price: 800_000,
    description: "A reliable work laptop required for all tech jobs. Keep it charged and your career on track.",
    shortDescription: "Required for tech jobs.",
    category: "JOB",
    asset: "work laptop",
    consumable: false,
    usable: false,
    itemType: "EQUIPMENT",
    effects: [],
  },
  {
    key: "medical_kit",
    name: "Medical Kit",
    price: 1_200_000,
    description: "A fully stocked medical kit required for all medical jobs. Non-negotiable in any healthcare setting.",
    shortDescription: "Required for medical jobs.",
    category: "JOB",
    asset: "medical kit",
    consumable: false,
    usable: false,
    itemType: "EQUIPMENT",
    effects: [],
  },
  {
    key: "business_briefcase",
    name: "Business Briefcase",
    price: 600_000,
    description: "A professional briefcase required for all business jobs. Carries your deals and your dignity.",
    shortDescription: "Required for business jobs.",
    category: "JOB",
    asset: "business briefcase",
    consumable: false,
    usable: false,
    itemType: "EQUIPMENT",
    effects: [],
  },
  {
    key: "legal_case_file",
    name: "Legal Case File",
    price: 700_000,
    description: "An official legal case file required for all legal jobs. The law waits for no one without their paperwork.",
    shortDescription: "Required for legal jobs.",
    category: "JOB",
    asset: "legal case file",
    consumable: false,
    usable: false,
    itemType: "EQUIPMENT",
    effects: [],
  },
  {
    key: "service_uniform",
    name: "Service Uniform",
    price: 250_000,
    description: "A clean service uniform required for all service jobs. Dress the part, play the part.",
    shortDescription: "Required for service jobs.",
    category: "JOB",
    asset: "service uniform",
    consumable: false,
    usable: false,
    itemType: "EQUIPMENT",
    effects: [],
  },
  {
    key: "mechanic_toolkit",
    name: "Mechanic Toolkit",
    price: 950_000,
    description: "A complete mechanic toolkit required for all trade jobs. Every bolt has a wrench and every wrench has a job.",
    shortDescription: "Required for trade jobs.",
    category: "JOB",
    asset: "mechanic toolkit",
    consumable: false,
    usable: false,
    itemType: "EQUIPMENT",
    effects: [],
  },
  {
    key: "freelance_starter_pack",
    name: "Freelance Starter Pack",
    price: 350_000,
    description: "A bundle of essentials required for all freelance jobs. Everything you need to look like you know what you're doing.",
    shortDescription: "Required for freelance jobs.",
    category: "JOB",
    asset: "freelance starter kit",
    consumable: false,
    usable: false,
    itemType: "EQUIPMENT",
    effects: [],
  },
  // Page 2 — consumables and buff items
  {
    key: "repair_coupon",
    name: "Repair Coupon",
    price: 300_000,
    description: "A voucher that fully repairs one broken or damaged piece of job equipment. Use it before your next shift to restore gear.",
    shortDescription: "Repairs one broken job item.",
    category: "JOB",
    asset: "repair token",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    maxStack: 5,
    effects: [{ type: "CUSTOM_MESSAGE", message: "Repair Coupon used!", trigger: "USE" }],
  },
  {
    key: "warranty_card",
    name: "Warranty Card",
    price: 450_000,
    description: "A protection card that blocks the next gear break event during a shift. Activates automatically when a break would occur.",
    shortDescription: "Blocks next gear break event.",
    category: "JOB",
    asset: "warranty card",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    maxStack: 3,
    effects: [{ type: "CUSTOM_MESSAGE", message: "Warranty Card activated! Your gear is protected from the next break event.", trigger: "USE" }],
  },
  {
    key: "stress_pills",
    name: "Stress Pills",
    price: 150_000,
    description: "A quick stress relief remedy. Reduces your job stress by 20 points after a rough shift or bad event.",
    shortDescription: "Reduces job stress by 20.",
    category: "JOB",
    asset: "stress pills",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [{ type: "CUSTOM_MESSAGE", message: "Stress Pills taken! Your job stress has been reduced.", trigger: "USE" }],
  },
  {
    key: "energy_flask",
    name: "Energy Flask",
    price: 200_000,
    description: "A concentrated energy drink that cuts your work cooldown by 2 hours. Perfect for grinding extra shifts.",
    shortDescription: "Reduces work cooldown by 2 hours.",
    category: "JOB",
    asset: "energy flask",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [{ type: "CUSTOM_MESSAGE", message: "Energy Flask consumed! Work cooldown reduced by 2 hours.", trigger: "USE" }],
  },
  {
    key: "focus_headphones",
    name: "Focus Headphones",
    price: 500_000,
    description: "Premium noise-canceling headphones that boost concentration. Doubles job XP earned for your next 3 shifts.",
    shortDescription: "+2x job XP for next 3 shifts.",
    category: "JOB",
    asset: "focus headphones",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    maxStack: 1,
    effects: [{ type: "CUSTOM_MESSAGE", message: "Focus Headphones on! Job XP doubled for your next 3 shifts.", trigger: "USE" }],
  },
  {
    key: "lucky_tie",
    name: "Lucky Tie",
    price: 400_000,
    description: "A suspiciously charming tie that improves your odds in random job events and interviews for 24 hours. Does not affect promotions.",
    shortDescription: "Boosts interview and job event odds for 24hr.",
    category: "JOB",
    asset: "lucky tie",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    maxStack: 1,
    effects: [{ type: "CUSTOM_MESSAGE", message: "Lucky Tie equipped! Job events will favour you for 24 hours.", trigger: "USE" }],
  },
  {
    key: "premium_tools_oil",
    name: "Premium Tools Oil",
    price: 350_000,
    description: "High-grade lubricant for tech and trade gear. Reduces gear durability loss for your next 5 shifts.",
    shortDescription: "Reduces gear wear for 5 shifts.",
    category: "JOB",
    asset: "premium tools oil",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [{ type: "CUSTOM_MESSAGE", message: "Premium Tools Oil applied! Gear will wear slower for 5 shifts.", trigger: "USE" }],
  },
  {
    key: "emergency_pager",
    name: "Emergency Pager",
    price: 600_000,
    description: "A backup pager that lets you redirect one critical job failure. Prevents one medical or urgent job event from failing your shift.",
    shortDescription: "Prevents one critical job event failure.",
    category: "JOB",
    asset: "emergency pager",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    maxStack: 2,
    effects: [{ type: "CUSTOM_MESSAGE", message: "Emergency Pager armed! Your next critical event will not fail your shift.", trigger: "USE" }],
  },
  {
    key: "overtime_contract",
    name: "Overtime Contract",
    price: 750_000,
    description: "A high-stakes contract that lets you take an immediate extra shift. The extra pay is real — but so are the stress and gear damage risk.",
    shortDescription: "Extra shift: +pay, +stress, +gear risk.",
    category: "JOB",
    asset: "overtime contract",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    maxStack: 1,
    effects: [{ type: "CUSTOM_MESSAGE", message: "Overtime Contract signed! Extra shift incoming.", trigger: "USE" }],
  },
  {
    key: "blackmarket_resume",
    name: "Black Market Resume",
    price: 900_000,
    description: "A fabricated résumé that boosts your promotion progress significantly. It might work perfectly — or blow up in your face.",
    shortDescription: "+big promotion progress, risk of backfire.",
    category: "JOB",
    asset: "blackmarket resume",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    maxStack: 1,
    effects: [{ type: "CUSTOM_MESSAGE", message: "Black Market Resume submitted!", trigger: "USE" }],
  },
  {
    key: "corporate_blessing",
    name: "Corporate Blessing",
    price: 1_500_000,
    description: "A mysterious golden memo from someone very important. Your next shift has a chance at a massive payout — but failure breaks your gear and tanks your stress.",
    shortDescription: "Huge payout chance, catastrophic failure risk.",
    category: "JOB",
    asset: "golden resume",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    maxStack: 1,
    effects: [{ type: "CUSTOM_MESSAGE", message: "Corporate Blessing invoked!", trigger: "USE" }],
  },
];

// ── Uni Store ────────────────────────────────────────────────────────────────
export const UNI_SHOP_CATALOG: ShopCatalogItem[] = [
  {
    key: "study_laptop",
    name: "Study Laptop",
    price: 180_000,
    description: "Required equipment for serious studying. Improves study XP by 1.25x for the next 5 sessions.",
    shortDescription: "1.25x study XP for 5 sessions.",
    category: "UNI",
    asset: "study laptop",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [{ type: "CUSTOM_MESSAGE", message: "Study Laptop activated!", trigger: "USE" }],
  },
  {
    key: "textbook_bundle",
    name: "Textbook Bundle",
    price: 120_000,
    description: "A stack of course books that boosts your next 3 study sessions with 1.35x XP.",
    shortDescription: "1.35x study XP for 3 sessions.",
    category: "UNI",
    asset: "textbook bundle",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [{ type: "CUSTOM_MESSAGE", message: "Textbook Bundle activated!", trigger: "USE" }],
  },
  {
    key: "lab_kit",
    name: "Lab Kit",
    price: 300_000,
    description: "Helps with science/lab-style study tasks. Reduces failure risk by 12% and gives 1.15x XP for 3 sessions.",
    shortDescription: "-12% fail + 1.15x XP for 3 sessions.",
    category: "UNI",
    asset: "lab kit",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [{ type: "CUSTOM_MESSAGE", message: "Lab Kit activated!", trigger: "USE" }],
  },
  {
    key: "calculator_pro",
    name: "Calculator Pro",
    price: 150_000,
    description: "Improves math/exam challenge odds with an 8% rescue chance on failures, plus 1.15x XP for 3 sessions.",
    shortDescription: "8% fail rescue + 1.15x XP for 3 sessions.",
    category: "UNI",
    asset: "calculator pro",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [{ type: "CUSTOM_MESSAGE", message: "Calculator Pro activated!", trigger: "USE" }],
  },
  {
    key: "coffee_thermos",
    name: "Coffee Thermos",
    price: 80_000,
    description: "Clears your active study cooldown. Always consumed on use — even if no cooldown is active.",
    shortDescription: "Clears study cooldown (always consumed).",
    category: "UNI",
    asset: "coffee thermos",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [{ type: "CUSTOM_MESSAGE", message: "Coffee Thermos used!", trigger: "USE" }],
  },
  {
    key: "focus_notes",
    name: "Focus Notes",
    price: 160_000,
    description: "Converts your next successful study session into extra education XP (+45 bonus).",
    shortDescription: "+45 bonus XP on next study success.",
    category: "UNI",
    asset: "focus notes",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [{ type: "CUSTOM_MESSAGE", message: "Focus Notes activated!", trigger: "USE" }],
  },
  {
    key: "cheat_sheet",
    name: "Cheat Sheet",
    price: 250_000,
    description: "Risky exam helper. 70% chance of a massive XP boost, but 30% chance of getting caught — losing education XP, gaining stress, and paying a wallet fine.",
    shortDescription: "70% exam boost / 30% severe penalty.",
    category: "UNI",
    asset: "cheat sheet",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [{ type: "CUSTOM_MESSAGE", message: "Cheat Sheet prepared!", trigger: "USE" }],
  },
  {
    key: "tutor_pass",
    name: "Tutor Pass",
    price: 400_000,
    description: "Guarantees better study rewards (1.6x XP) and reduces failure chance by 15% for your next session.",
    shortDescription: "1.6x XP + 15% fail rescue, 1 session.",
    category: "UNI",
    asset: "tutor pass",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [{ type: "CUSTOM_MESSAGE", message: "Tutor Pass activated!", trigger: "USE" }],
  },
  {
    key: "scholarship_letter",
    name: "Scholarship Letter",
    price: 750_000,
    description: "Submit for a chance at a large reward. 45% coin payout, 35% education XP, 20% rejected. 1-hour cooldown between uses.",
    shortDescription: "Immediate roll for coin/XP reward.",
    category: "UNI",
    asset: "scholarship letter",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [{ type: "CUSTOM_MESSAGE", message: "Scholarship Letter submitted!", trigger: "USE" }],
  },
];

export const COCK_SHOP_CATALOG: ShopCatalogItem[] = [
  {
    key: "basic_feed",
    name: "Basic Feed",
    price: 10_000,
    description: "Simple grain mix for your chicken. A daily staple that provides steady XP growth. +10 XP per use.",
    shortDescription: "+10 XP per feed.",
    category: "COCK",
    asset: "basic_feed",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [{ type: "CUSTOM_MESSAGE", message: "Use with `!use basic feed [amount]`", trigger: "BUY" }],
  },
  {
    key: "protein_feed",
    name: "Protein Feed",
    price: 45_000,
    description: "High-protein formula for accelerated growth. +35 XP per use.",
    shortDescription: "+35 XP per feed.",
    category: "COCK",
    asset: "protein_feed",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [{ type: "CUSTOM_MESSAGE", message: "Use with `!use protein feed [amount]`", trigger: "BUY" }],
  },
  {
    key: "agility_vitamins",
    name: "Agility Vitamins",
    price: 60_000,
    description: "Performance-enhancing vitamins. Grants +1 to a random stat (Strength, Agility, or Defense). Each stat caps at 10.",
    shortDescription: "+1 random stat (cap 10).",
    category: "COCK",
    asset: "agility_vitamins",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [{ type: "CUSTOM_MESSAGE", message: "+1 random stat to your chicken.", trigger: "USE" }],
  },
  {
    key: "feather_bandage",
    name: "Feather Bandage",
    price: 75_000,
    description: "Specially designed bandage for cockfighting injuries. Instantly clears your chicken's injury timer.",
    shortDescription: "Heal injured chicken instantly.",
    category: "COCK",
    asset: "feather_bandage",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [{ type: "CUSTOM_MESSAGE", message: "Clears chicken injury.", trigger: "USE" }],
  },
  {
    key: "training_whistle",
    name: "Training Whistle",
    price: 120_000,
    description: "A sharp whistle that instantly completes your chicken's current training session, granting the stat immediately.",
    shortDescription: "Complete training instantly.",
    category: "COCK",
    asset: "training_whistle",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [{ type: "CUSTOM_MESSAGE", message: "Completes active training.", trigger: "USE" }],
  },
  {
    key: "iron_spurs",
    name: "Iron Spurs",
    price: 300_000,
    description: "Razor-sharp iron spurs that attach to your chicken's talons. Equips to the weapon slot. +3 Strength.",
    shortDescription: "Weapon: +3 Strength.",
    category: "COCK",
    asset: "iron_spurs",
    consumable: false,
    usable: true,
    itemType: "EQUIPMENT",
    effects: [{ type: "CUSTOM_MESSAGE", message: "Equips to weapon slot.", trigger: "USE" }],
  },
  {
    key: "guard_vest",
    name: "Guard Vest",
    price: 350_000,
    description: "Reinforced protective vest for your chicken. Equips to the armor slot. +4 Defense.",
    shortDescription: "Armor: +4 Defense.",
    category: "COCK",
    asset: "guard_vest",
    consumable: false,
    usable: true,
    itemType: "EQUIPMENT",
    effects: [{ type: "CUSTOM_MESSAGE", message: "Equips to armor slot.", trigger: "USE" }],
  },
  {
    key: "champion_feed",
    name: "Champion Feed",
    price: 500_000,
    description: "Premium championship-grade nutrition. +120 XP per use. Best value when daily feed slots are limited.",
    shortDescription: "+120 XP per feed (premium).",
    category: "COCK",
    asset: "champion_feed",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [{ type: "CUSTOM_MESSAGE", message: "Use with `!use champion feed [amount]`", trigger: "BUY" }],
  },
  {
    key: "phoenix_serum",
    name: "Phoenix Serum",
    price: 900_000,
    description: "Emergency recovery serum. Instantly clears injury AND completes active training. 24-hour cooldown between uses.",
    shortDescription: "Full recovery (heal + finish training). 24h CD.",
    category: "COCK",
    asset: "phoenix_serum",
    consumable: true,
    usable: true,
    itemType: "CONSUMABLE",
    effects: [{ type: "CUSTOM_MESSAGE", message: "Full chicken recovery. 24h cooldown.", trigger: "USE" }],
  },
];

export const COCK_SYSTEM_ITEMS: ShopCatalogItem[] = [
  {
    key: "chicken",
    name: "Chicken",
    price: 25_000,
    description: "Your fighting companion. Each chicken has a unique trait.",
    shortDescription: "A cockfighting chicken.",
    category: "COCK",
    asset: "cockstore_mascot",
    consumable: false,
    usable: false,
    itemType: "COLLECTIBLE",
    effects: [],
    maxStack: 1,
  },
];

export const SHOP_CATALOG: ShopCatalogItem[] = [
  ...GENERAL_SHOP_CATALOG,
  ...HUNT_SHOP_CATALOG,
  ...JOB_SHOP_CATALOG,
  ...UNI_SHOP_CATALOG,
  ...COCK_SHOP_CATALOG,
];

export function getCatalogByCategory(category: ShopCategory): ShopCatalogItem[] {
  return SHOP_CATALOG.filter(item => item.category === category);
}

export function getCatalogItem(key: string): ShopCatalogItem | undefined {
  return SHOP_CATALOG.find(item => item.key === key);
}
