import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { LandingNavbar } from "@/components/LandingNavbar";
import { Footer } from "@/components/Footer";
import { Panel } from "@/components/ui/Panel";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "How Fortuna collects, uses, and protects your data — on Discord and on this website.",
};

export default async function PolicyPage() {
  const session = await getServerSession(authOptions);

  return (
    <main className="min-h-screen bg-bg">
      <LandingNavbar user={session?.user} />

      <div className="mx-auto max-w-3xl px-6 pb-24 pt-16">
        <h1 className="font-display text-4xl font-extrabold tracking-tight text-ink">
          Privacy Policy
        </h1>
        <p className="mt-3 text-lg leading-relaxed text-muted">
          How Fortuna collects, uses, and protects your data — on Discord and
          on this website.
        </p>
        <p className="mt-2 text-sm text-muted">
          Effective Date: July 6, 2026
        </p>

        <div className="mt-10 space-y-6">
          <Panel className="p-8">
            <p className="leading-relaxed text-muted">
              This Privacy Policy (&quot;Policy&quot;) describes how the
              development team of Fortuna (&quot;Service Provider,&quot;
              &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) collects,
              uses, discloses, and protects your data when you use the Fortuna
              bot on the Discord platform or this website (together, the
              &quot;Service&quot;).
              <br />
              <br />
              By using the Service, you consent to the data practices
              described in this Policy. If you do not agree with this Policy,
              please do not use the Service.
            </p>
          </Panel>

          <PolicySection title="1. Data We Collect">
            <p>
              Fortuna operates a single game account per Discord user. Your
              account and its data are shared across every server where you
              use the bot — we do not maintain separate per-server economies.
            </p>

            <div>
              <h3 className="mb-2 font-bold text-ink">1.1. Identity Data</h3>
              <ul className="list-disc space-y-2 pl-5">
                <li>
                  <strong className="text-ink">Discord account:</strong> your
                  Discord User ID (the primary identifier for your game
                  account), username, and avatar URL, as provided by the
                  Discord API.
                </li>
                <li>
                  <strong className="text-ink">Website sign-in:</strong> if
                  you log in to this website with Discord, we receive the same
                  identity data through Discord&apos;s OAuth flow and store a
                  session cookie to keep you signed in. We never see or store
                  your Discord password.
                </li>
              </ul>
            </div>

            <div>
              <h3 className="mb-2 font-bold text-ink">1.2. Game Data</h3>
              <p className="mb-2">
                Data generated by playing Fortuna, all linked to your Discord
                User ID:
              </p>
              <ul className="list-disc space-y-2 pl-5">
                <li>
                  <strong className="text-ink">Economy records:</strong>{" "}
                  wallet and bank balances, transaction history, transfers,
                  fixed and recurring deposits.
                </li>
                <li>
                  <strong className="text-ink">Credit data:</strong> virtual
                  credit card accounts, statements, payment history, and your
                  in-game credit score.
                </li>
                <li>
                  <strong className="text-ink">Progression data:</strong>{" "}
                  jobs, career history, education and degrees, stress levels,
                  daily quest progress, and streaks.
                </li>
                <li>
                  <strong className="text-ink">Possessions:</strong>{" "}
                  inventory items, properties, stock holdings, animals, and
                  cosmetics.
                </li>
                <li>
                  <strong className="text-ink">Social data:</strong> in-game
                  marriage status, partner, and shared vault balances.
                </li>
              </ul>
            </div>

            <div>
              <h3 className="mb-2 font-bold text-ink">
                1.3. Server and Usage Data
              </h3>
              <ul className="list-disc space-y-2 pl-5">
                <li>
                  <strong className="text-ink">Server settings:</strong> the
                  only per-server configuration Fortuna stores is the Discord
                  Server (Guild) ID and its chosen command prefix.
                </li>
                <li>
                  <strong className="text-ink">Context metadata:</strong>{" "}
                  server, channel, and message IDs may be attached to
                  transaction and game logs for auditing, support, and
                  anti-abuse purposes.
                </li>
                <li>
                  <strong className="text-ink">Usage metadata:</strong>{" "}
                  timestamps of account creation, command usage, and cooldown
                  tracking.
                </li>
              </ul>
            </div>
          </PolicySection>

          <PolicySection title="2. Purpose and Legal Basis of Processing">
            <p>
              We process this data under the following legal bases and for
              the purposes outlined here:
            </p>
            <ul className="list-disc space-y-3 pl-5">
              <li>
                <strong className="text-ink">Contractual necessity:</strong>{" "}
                to operate the game — maintaining your account balance,
                possessions, and progress across all servers where you play.
              </li>
              <li>
                <strong className="text-ink">Legitimate interests:</strong>{" "}
                to keep the game fair and functional — preventing fraud,
                automation, and exploits, enforcing our Terms of Service, and
                analyzing Service performance.
              </li>
              <li>
                <strong className="text-ink">
                  Compliance with legal obligations:
                </strong>{" "}
                to comply with applicable laws, regulations, or valid legal
                processes.
              </li>
            </ul>
          </PolicySection>

          <PolicySection title="3. Disclosure of Information">
            <ul className="list-disc space-y-3 pl-5">
              <li>
                <strong className="text-ink">No commercial transfer:</strong>{" "}
                we do not sell, license, lease, or commercially transfer user
                data to advertisers or data brokers.
              </li>
              <li>
                <strong className="text-ink">Platform services:</strong> the
                Service runs on Discord; your interactions with the bot are
                also subject to Discord&apos;s own Privacy Policy. If you use
                the vote reward, your Discord User ID is checked against the
                Top.gg API to verify your vote.
              </li>
              <li>
                <strong className="text-ink">
                  Infrastructure providers:
                </strong>{" "}
                we use third-party hosting, database, and caching providers
                solely to run the Service. These providers process data on
                our behalf.
              </li>
              <li>
                <strong className="text-ink">Legal requirements:</strong> we
                may disclose data when we believe in good faith that doing so
                is required by a judicial proceeding, court order, or legal
                process.
              </li>
            </ul>
          </PolicySection>

          <PolicySection title="4. Data Security and Retention">
            <p>
              We implement technical and organizational measures designed to
              protect your data from unauthorized access, accidental loss,
              disclosure, or destruction, including encryption in transit and
              access controls.
            </p>
            <p>
              We retain data only as long as necessary for the purposes it
              was collected — primarily, for as long as you have an active
              game account. When your data is deleted (see Section 5), it is
              removed from our active databases.
            </p>
          </PolicySection>

          <PolicySection title="5. Your Rights and Control">
            <p>
              Subject to applicable law, you have the following rights over
              your data:
            </p>
            <ul className="list-disc space-y-2 pl-5">
              <li>
                <strong className="text-ink">Right to access:</strong> most
                of your game data is visible in-game at any time — the{" "}
                <code className="rounded border border-line bg-panel-2 px-1.5 py-0.5 font-mono text-sm text-ink">
                  !profile
                </code>{" "}
                command shows your account overview. For a full copy of the
                data we hold about you, submit a request via our Support
                Server.
              </li>
              <li>
                <strong className="text-ink">
                  Right to erasure (&quot;right to be forgotten&quot;):
                </strong>{" "}
                you may request permanent deletion of your game account via
                our Support Server. Because your account is shared across
                servers, deletion removes your economy data everywhere the
                bot operates and cannot be undone.
              </li>
              <li>
                <strong className="text-ink">Right to rectification:</strong>{" "}
                you may request correction of inaccurate or incomplete data.
              </li>
            </ul>
          </PolicySection>

          <PolicySection title="6. International Data Transfers">
            <p>
              The Service may be hosted on infrastructure located in
              jurisdictions other than your own. By using the Service, you
              acknowledge that your data may be transferred to and processed
              in jurisdictions with data protection laws that differ from
              those of your place of residence.
            </p>
          </PolicySection>

          <PolicySection title="7. Children's Privacy">
            <p>
              The Service is available only to users who meet Discord&apos;s
              minimum age requirements (13 years, or higher where local law
              requires). We do not knowingly collect data from anyone below
              that age; if we learn that we have, we will delete it.
            </p>
          </PolicySection>

          <PolicySection title="8. Amendments">
            <p>
              We may update this Policy from time to time. Material changes
              will be announced via the Service or our official support
              channels, and the effective date above will be revised. Your
              continued use of the Service after such notice constitutes
              acceptance of the updated Policy.
            </p>
          </PolicySection>

          <PolicySection title="Contact">
            <p>
              For questions about this Policy or to exercise your data
              rights, contact us via our official Support Server.
            </p>
            <a
              href="https://discord.gg/Y5P44UCH2Y"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-block font-medium text-gold hover:text-gold-deep"
            >
              Join Support Server
            </a>
          </PolicySection>
        </div>
      </div>

      <Footer />
    </main>
  );
}

function PolicySection({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <Panel className="p-8">
      <h2 className="font-display text-2xl font-bold text-ink">{title}</h2>
      <div className="mt-4 space-y-4 leading-relaxed text-muted">
        {children}
      </div>
    </Panel>
  );
}
